### PR TITLE
Update dependencies related to parsing

### PR DESCRIPTION
**Pull request by honzajavorek**
Updating all dependencies related to parsing except of the `fury-adapter-apib-parser`, which causes problems from version 0.4.0 (see below in original comments).

------

This is a follow-up to https://github.com/apiaryio/dredd-transactions/pull/73.

### CODE REVIEW

**Comment by w-vi** [comment]
JS and C++ parsers use the same code base so I doubt there is a difference I'd suspect the build setup. Are protagonist and drafter.js  of the same version?

**Comment by honzajavorek** [comment]
@w-vi @kylef I'm not kidding. I just managed to reproduce the problem on CI:

image

**Comment by kylef** [comment]
@honzajavorek https://github.com/apiaryio/fury-adapter-apib-parser/pull/15 should fix this problem.

**Comment by honzajavorek** [comment]
@kylef I've updated the PR. Now it doesn't update the `fury-adapter-apib-parser`, see updated description.

**Pull request merged**
