### PR TITLE
Compile URI using minim

### PR DESCRIPTION
**Pull request by honzajavorek**
This PR makes sure everything in the `compile-uri` directory introduced in https://github.com/apiaryio/dredd-transactions/pull/84 uses minim instead of raw refract.

### CODE REVIEW

**Comment by honzajavorek** [comment]
I'm getting timeouts in the tests 😞

**Comment by michalholasek** [comment]
@honzajavorek So we are running into `minim` performance problems once again I suppose?

**Comment by honzajavorek** [comment]
Depends. Either that or it's overuse of serialize/deserialize (which should be temporary though). Let's continue with this after investigating why the performance dropped in #87.

**Comment by honzajavorek** [comment]
When resumed, this PR needs to incorporate what happened in https://github.com/apiaryio/dredd-transactions/pull/94 and to fix several things introduced in https://github.com/apiaryio/dredd-transactions/pull/94:

- Change expect to assert so the new tests are aligned with the rest of the codebase
- Merge the code in `compile-params.coffee` somehow
- Leverage the new `src/refract-serialization.coffee` in `compile-params.coffee`

**Comment by honzajavorek** [comment]
Superseded by https://github.com/apiaryio/dredd-transactions/pull/97.

**Pull request closed without merging**
