### PR TITLE
Update fury to version 3.0.0-beta.7

### PR DESCRIPTION
**Pull request by kylef**
Fixes https://github.com/apiaryio/dredd-transactions/pull/169

### CODE REVIEW

**Comment by pksunkara** [comment]
@honzajavorek Need a dredd release on this. 🔜

**Comment by kylef** [comment]
> Need a dredd release on this

I wouldn't say that is necessary, this change brings no bug fixes nor features to Dredd. The changes are to 0.6 serialisation which doesn't effect Dredd?

**Comment by pksunkara** [comment]
Dredd is being used in our API parsing services CI. Since we are updating fury there, we want to have compatible fury in dredd too.

**Comment by pksunkara** [comment]
A minor patch release should be okay.

**Pull request merged**
